/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: t4V3p66SUxNrC7VqQmN1Jm
// Component: iurfTdSHt9sG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ButtonCategory2 from "../../ButtonCategory2"; // plasmic-import: nRo5fxjIuUgU/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import plasmic_library_tailwind_3_4_colors_css from "../library_tailwind_3_4_color_tokens/plasmic.module.css"; // plasmic-import: 5ZtnypMovRHeeP3YTdPCYL/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: t4V3p66SUxNrC7VqQmN1Jm/projectcss
import sty from "./PlasmicButtonCategory.module.css"; // plasmic-import: iurfTdSHt9sG/css

createPlasmicElementProxy;

export type PlasmicButtonCategory__VariantMembers = {};
export type PlasmicButtonCategory__VariantsArgs = {};
type VariantPropType = keyof PlasmicButtonCategory__VariantsArgs;
export const PlasmicButtonCategory__VariantProps = new Array<VariantPropType>();

export type PlasmicButtonCategory__ArgsType = {};
type ArgPropType = keyof PlasmicButtonCategory__ArgsType;
export const PlasmicButtonCategory__ArgProps = new Array<ArgPropType>();

export type PlasmicButtonCategory__OverridesType = {
  root?: Flex__<"div">;
  buttonCategory?: Flex__<"div">;
  link?: Flex__<"a"> & Partial<LinkProps>;
  buttonCategory2?: Flex__<typeof ButtonCategory2>;
};

export interface DefaultButtonCategoryProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicButtonCategory__RenderFunc(props: {
  variants: PlasmicButtonCategory__VariantsArgs;
  args: PlasmicButtonCategory__ArgsType;
  overrides: PlasmicButtonCategory__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        plasmic_library_tailwind_3_4_colors_css.plasmic_tokens,
        plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"buttonCategory"}
        data-plasmic-override={overrides.buttonCategory}
        className={classNames(projectcss.all, sty.buttonCategory)}
      >
        <PlasmicLink__
          data-plasmic-name={"link"}
          data-plasmic-override={overrides.link}
          className={classNames(
            projectcss.all,
            projectcss.a,
            projectcss.__wab_text,
            sty.link
          )}
          component={Link}
          platform={"nextjs"}
        >
          {"News"}
        </PlasmicLink__>
      </div>
      <ButtonCategory2
        data-plasmic-name={"buttonCategory2"}
        data-plasmic-override={overrides.buttonCategory2}
        className={classNames("__wab_instance", sty.buttonCategory2)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "buttonCategory", "link", "buttonCategory2"],
  buttonCategory: ["buttonCategory", "link"],
  link: ["link"],
  buttonCategory2: ["buttonCategory2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  buttonCategory: "div";
  link: "a";
  buttonCategory2: typeof ButtonCategory2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonCategory__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonCategory__VariantsArgs;
    args?: PlasmicButtonCategory__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButtonCategory__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButtonCategory__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButtonCategory__ArgProps,
          internalVariantPropNames: PlasmicButtonCategory__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButtonCategory__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButtonCategory";
  } else {
    func.displayName = `PlasmicButtonCategory.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonCategory = Object.assign(
  // Top-level PlasmicButtonCategory renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    buttonCategory: makeNodeComponent("buttonCategory"),
    link: makeNodeComponent("link"),
    buttonCategory2: makeNodeComponent("buttonCategory2"),

    // Metadata about props expected for PlasmicButtonCategory
    internalVariantProps: PlasmicButtonCategory__VariantProps,
    internalArgProps: PlasmicButtonCategory__ArgProps
  }
);

export default PlasmicButtonCategory;
/* prettier-ignore-end */
